"""initial schema

Revision ID: 5bb2e3cd1c8b
Revises: 
Create Date: 2026-07-05 01:32:34.492970
"""
from alembic import op
import sqlalchemy as sa


revision = '5bb2e3cd1c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sohib', sa.String(length=8), nullable=True),
    sa.Column('iftikhor', sa.String(length=8), nullable=True),
    sa.Column('dovud', sa.String(length=8), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_created_by'), ['created_by'], unique=False)

    op.create_table('audit_log',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource'), ['resource'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('barter_operations',
    sa.Column('from_business', sa.String(length=36), nullable=False),
    sa.Column('to_business', sa.String(length=36), nullable=False),
    sa.Column('nomenclature_id', sa.String(length=36), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('price_frozen', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barter_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barter_operations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_barter_operations_created_by'), ['created_by'], unique=False)

    op.create_table('businesses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_created_by'), ['created_by'], unique=False)

    op.create_table('calendar_events',
    sa.Column('owner_scope', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participants_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_created_by'), ['created_by'], unique=False)

    op.create_table('capacity_records',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('output_qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capacity_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capacity_records_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_capacity_records_created_by'), ['created_by'], unique=False)

    op.create_table('cash_registers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_registers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_registers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_registers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_registers_created_by'), ['created_by'], unique=False)

    op.create_table('clients',
    sa.Column('counterparty_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_created_by'), ['created_by'], unique=False)

    op.create_table('construction_objects',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('construction_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_construction_objects_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_construction_objects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_construction_objects_created_by'), ['created_by'], unique=False)

    op.create_table('counterparties',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('inn', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparties_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparties_created_by'), ['created_by'], unique=False)

    op.create_table('debts',
    sa.Column('from_business', sa.String(length=36), nullable=False),
    sa.Column('to_business', sa.String(length=36), nullable=False),
    sa.Column('counterparty_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('basis_ref', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_from_business'), ['from_business'], unique=False)
        batch_op.create_index(batch_op.f('ix_debts_to_business'), ['to_business'], unique=False)

    op.create_table('escalations',
    sa.Column('act_id', sa.String(length=36), nullable=True),
    sa.Column('remark_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('to_owners', sa.JSON(), nullable=True),
    sa.Column('bypass_business', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalations_created_by'), ['created_by'], unique=False)

    op.create_table('fractions',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fractions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fractions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fractions_created_by'), ['created_by'], unique=False)

    op.create_table('fuel_consumptions',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('liters', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('norm_liters', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_consumptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_consumptions_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_consumptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_consumptions_created_by'), ['created_by'], unique=False)

    op.create_table('geodesy_requests',
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geodesy_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geodesy_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geodesy_requests_created_by'), ['created_by'], unique=False)

    op.create_table('inspection_acts',
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_acts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_acts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_acts_created_by'), ['created_by'], unique=False)

    op.create_table('inspection_plans',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scheduled_at', sa.Date(), nullable=True),
    sa.Column('planned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_plans_created_by'), ['created_by'], unique=False)

    op.create_table('inventories',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventories_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventories_created_by'), ['created_by'], unique=False)

    op.create_table('limits',
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('resource', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('set_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_limits_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_limits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_limits_created_by'), ['created_by'], unique=False)

    op.create_table('orders',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('counterparty_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('mark', sa.String(length=64), nullable=True),
    sa.Column('volume', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload_frozen', sa.JSON(), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('reversal_of', sa.String(length=36), nullable=True),
    sa.Column('reversed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['reversal_of'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_created_by'), ['created_by'], unique=False)

    op.create_table('period_close',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('closed_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period', name='uq_period_close')
    )
    with op.batch_alter_table('period_close', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_close_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_close_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_close_created_by'), ['created_by'], unique=False)

    op.create_table('permissions',
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', 'scope', name='uq_permission')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_resource'), ['resource'], unique=False)

    op.create_table('production_shifts',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_shifts_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_shifts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_shifts_created_by'), ['created_by'], unique=False)

    op.create_table('projects',
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_by'), ['created_by'], unique=False)

    op.create_table('quality_passes',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('sample_ref', sa.String(length=120), nullable=True),
    sa.Column('test_day', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=200), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_passes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_passes_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_passes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_passes_created_by'), ['created_by'], unique=False)

    op.create_table('recipes',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('mark', sa.String(length=64), nullable=False),
    sa.Column('frozen_json', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_created_by'), ['created_by'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_created_by'), ['created_by'], unique=False)

    op.create_table('supervision_objects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manager_user_id', sa.String(length=36), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supervision_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervision_objects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supervision_objects_created_by'), ['created_by'], unique=False)

    op.create_table('supervision_payments',
    sa.Column('supervision_object_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('collected_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supervision_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervision_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supervision_payments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_supervision_payments_supervision_object_id'), ['supervision_object_id'], unique=False)

    op.create_table('supply_requests',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supply_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_requests_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_requests_created_by'), ['created_by'], unique=False)

    op.create_table('tasks',
    sa.Column('assigned_to', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_scope', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_by'), ['created_by'], unique=False)

    op.create_table('units',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_created_by'), ['created_by'], unique=False)

    op.create_table('users',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('vehicles',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('plate', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_created_by'), ['created_by'], unique=False)

    op.create_table('warehouse_movements',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('nomenclature_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=True),
    sa.Column('basis_ref', sa.String(length=200), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('reversal_of', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_movements_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_movements_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_movements_nomenclature_id'), ['nomenclature_id'], unique=False)

    op.create_table('access_grants',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('disabled_by', sa.String(length=36), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_grants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_user_id'), ['user_id'], unique=False)

    op.create_table('briefs',
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('price_frozen', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefs_created_by'), ['created_by'], unique=False)

    op.create_table('contracts',
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('brief_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('schedule_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_created_by'), ['created_by'], unique=False)

    op.create_table('employees',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('salary', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('fired_at', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=False)

    op.create_table('estimates',
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('plan_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fact_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['construction_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_estimates_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_estimates_object_id'), ['object_id'], unique=False)

    op.create_table('fraction_outputs',
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('fraction_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['production_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraction_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraction_outputs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraction_outputs_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraction_outputs_shift_id'), ['shift_id'], unique=False)

    op.create_table('inkassaciya',
    sa.Column('cash_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('calc_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fact_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discrepancy', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_by', sa.String(length=36), nullable=True),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('accepted_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shift_ref', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_registers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inkassaciya', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inkassaciya_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inkassaciya_cash_id'), ['cash_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inkassaciya_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inkassaciya_created_by'), ['created_by'], unique=False)

    op.create_table('money_movements',
    sa.Column('cash_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('income_stage', sa.String(length=16), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('article', sa.String(length=200), nullable=True),
    sa.Column('basis_ref', sa.String(length=200), nullable=True),
    sa.Column('counterparty_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_reversal', sa.Boolean(), nullable=False),
    sa.Column('reversal_of', sa.String(length=36), nullable=True),
    sa.Column('reversed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cash_id'], ['cash_registers.id'], ),
    sa.ForeignKeyConstraint(['reversal_of'], ['money_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('money_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_money_movements_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_money_movements_cash_id'), ['cash_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_money_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_money_movements_created_by'), ['created_by'], unique=False)

    op.create_table('nomenclature',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('nomenclature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nomenclature_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nomenclature_created_by'), ['created_by'], unique=False)

    op.create_table('owners',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owners_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_owners_created_by'), ['created_by'], unique=False)

    op.create_table('production_tasks',
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('cost_frozen', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_tasks_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_tasks_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_production_tasks_order_id'), ['order_id'], unique=False)

    op.create_table('purchases',
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('limit_ok', sa.Boolean(), nullable=False),
    sa.Column('approval_ref', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['supply_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_created_by'), ['created_by'], unique=False)

    op.create_table('remarks',
    sa.Column('act_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['inspection_acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remarks_act_id'), ['act_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remarks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_remarks_created_by'), ['created_by'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('shipping_tickets',
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle', sa.String(length=100), nullable=True),
    sa.Column('driver_user_id', sa.String(length=36), nullable=True),
    sa.Column('nomenclature_id', sa.String(length=36), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('shipped_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_tickets_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_tickets_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipping_tickets_order_id'), ['order_id'], unique=False)

    op.create_table('stages',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stages_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_stages_project_id'), ['project_id'], unique=False)

    op.create_table('supervision_rounds',
    sa.Column('supervision_object_id', sa.String(length=36), nullable=False),
    sa.Column('photos_json', sa.JSON(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['supervision_object_id'], ['supervision_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supervision_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supervision_rounds_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_supervision_rounds_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_supervision_rounds_supervision_object_id'), ['supervision_object_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('counterparty_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_created_by'), ['created_by'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('deliveries',
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('driver_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['shipping_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_created_by'), ['created_by'], unique=False)

    op.create_table('quotes',
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('items_json', sa.JSON(), nullable=True),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['supply_requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotes_request_id'), ['request_id'], unique=False)

    op.create_table('receipts',
    sa.Column('purchase_id', sa.String(length=36), nullable=True),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('nomenclature_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('shortage', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('surplus', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_created_by'), ['created_by'], unique=False)

    op.create_table('salaries',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('accrued', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salaries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_salaries_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_salaries_employee_id'), ['employee_id'], unique=False)

    op.create_table('timesheets',
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheets_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_timesheets_employee_id'), ['employee_id'], unique=False)

    op.create_table('warehouse_stock',
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('nomenclature_id', sa.String(length=36), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['nomenclature_id'], ['nomenclature.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'nomenclature_id', 'status', name='uq_stock')
    )
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_stock_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_stock_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_stock_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_stock_nomenclature_id'), ['nomenclature_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_nomenclature_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_created_by'))
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_created_at'))
        batch_op.drop_index(batch_op.f('ix_warehouse_stock_business_id'))

    op.drop_table('warehouse_stock')
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheets_employee_id'))
        batch_op.drop_index(batch_op.f('ix_timesheets_created_by'))
        batch_op.drop_index(batch_op.f('ix_timesheets_created_at'))

    op.drop_table('timesheets')
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salaries_employee_id'))
        batch_op.drop_index(batch_op.f('ix_salaries_created_by'))
        batch_op.drop_index(batch_op.f('ix_salaries_created_at'))

    op.drop_table('salaries')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_created_by'))
        batch_op.drop_index(batch_op.f('ix_receipts_created_at'))
        batch_op.drop_index(batch_op.f('ix_receipts_business_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_request_id'))
        batch_op.drop_index(batch_op.f('ix_quotes_created_by'))
        batch_op.drop_index(batch_op.f('ix_quotes_created_at'))

    op.drop_table('quotes')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_created_by'))
        batch_op.drop_index(batch_op.f('ix_deliveries_created_at'))
        batch_op.drop_index(batch_op.f('ix_deliveries_business_id'))

    op.drop_table('deliveries')
    op.drop_table('user_roles')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_created_by'))
        batch_op.drop_index(batch_op.f('ix_suppliers_created_at'))

    op.drop_table('suppliers')
    with op.batch_alter_table('supervision_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervision_rounds_supervision_object_id'))
        batch_op.drop_index(batch_op.f('ix_supervision_rounds_created_by'))
        batch_op.drop_index(batch_op.f('ix_supervision_rounds_created_at'))

    op.drop_table('supervision_rounds')
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_project_id'))
        batch_op.drop_index(batch_op.f('ix_stages_created_by'))
        batch_op.drop_index(batch_op.f('ix_stages_created_at'))

    op.drop_table('stages')
    with op.batch_alter_table('shipping_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_tickets_order_id'))
        batch_op.drop_index(batch_op.f('ix_shipping_tickets_created_by'))
        batch_op.drop_index(batch_op.f('ix_shipping_tickets_created_at'))
        batch_op.drop_index(batch_op.f('ix_shipping_tickets_business_id'))

    op.drop_table('shipping_tickets')
    op.drop_table('role_permissions')
    with op.batch_alter_table('remarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remarks_created_by'))
        batch_op.drop_index(batch_op.f('ix_remarks_created_at'))
        batch_op.drop_index(batch_op.f('ix_remarks_act_id'))

    op.drop_table('remarks')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_created_by'))
        batch_op.drop_index(batch_op.f('ix_purchases_created_at'))
        batch_op.drop_index(batch_op.f('ix_purchases_business_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('production_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_tasks_order_id'))
        batch_op.drop_index(batch_op.f('ix_production_tasks_created_by'))
        batch_op.drop_index(batch_op.f('ix_production_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_production_tasks_business_id'))

    op.drop_table('production_tasks')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owners_created_by'))
        batch_op.drop_index(batch_op.f('ix_owners_created_at'))

    op.drop_table('owners')
    with op.batch_alter_table('nomenclature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nomenclature_created_by'))
        batch_op.drop_index(batch_op.f('ix_nomenclature_created_at'))

    op.drop_table('nomenclature')
    with op.batch_alter_table('money_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_money_movements_created_by'))
        batch_op.drop_index(batch_op.f('ix_money_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_money_movements_cash_id'))
        batch_op.drop_index(batch_op.f('ix_money_movements_business_id'))

    op.drop_table('money_movements')
    with op.batch_alter_table('inkassaciya', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inkassaciya_created_by'))
        batch_op.drop_index(batch_op.f('ix_inkassaciya_created_at'))
        batch_op.drop_index(batch_op.f('ix_inkassaciya_cash_id'))
        batch_op.drop_index(batch_op.f('ix_inkassaciya_business_id'))

    op.drop_table('inkassaciya')
    with op.batch_alter_table('fraction_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraction_outputs_shift_id'))
        batch_op.drop_index(batch_op.f('ix_fraction_outputs_created_by'))
        batch_op.drop_index(batch_op.f('ix_fraction_outputs_created_at'))

    op.drop_table('fraction_outputs')
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimates_object_id'))
        batch_op.drop_index(batch_op.f('ix_estimates_created_by'))
        batch_op.drop_index(batch_op.f('ix_estimates_created_at'))

    op.drop_table('estimates')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_created_by'))
        batch_op.drop_index(batch_op.f('ix_employees_created_at'))
        batch_op.drop_index(batch_op.f('ix_employees_business_id'))

    op.drop_table('employees')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_created_by'))
        batch_op.drop_index(batch_op.f('ix_contracts_created_at'))
        batch_op.drop_index(batch_op.f('ix_contracts_client_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefs_created_by'))
        batch_op.drop_index(batch_op.f('ix_briefs_created_at'))
        batch_op.drop_index(batch_op.f('ix_briefs_client_id'))

    op.drop_table('briefs')
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_created_by'))
        batch_op.drop_index(batch_op.f('ix_access_grants_created_at'))

    op.drop_table('access_grants')
    with op.batch_alter_table('warehouse_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_movements_nomenclature_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_movements_created_by'))
        batch_op.drop_index(batch_op.f('ix_warehouse_movements_created_at'))
        batch_op.drop_index(batch_op.f('ix_warehouse_movements_business_id'))

    op.drop_table('warehouse_movements')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_created_by'))
        batch_op.drop_index(batch_op.f('ix_vehicles_created_at'))
        batch_op.drop_index(batch_op.f('ix_vehicles_business_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_created_by'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_created_by'))
        batch_op.drop_index(batch_op.f('ix_units_created_at'))

    op.drop_table('units')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_created_by'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_assigned_to'))

    op.drop_table('tasks')
    with op.batch_alter_table('supply_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_requests_created_by'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_supply_requests_business_id'))

    op.drop_table('supply_requests')
    with op.batch_alter_table('supervision_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervision_payments_supervision_object_id'))
        batch_op.drop_index(batch_op.f('ix_supervision_payments_created_by'))
        batch_op.drop_index(batch_op.f('ix_supervision_payments_created_at'))

    op.drop_table('supervision_payments')
    with op.batch_alter_table('supervision_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supervision_objects_created_by'))
        batch_op.drop_index(batch_op.f('ix_supervision_objects_created_at'))

    op.drop_table('supervision_objects')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_created_by'))
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_created_by'))
        batch_op.drop_index(batch_op.f('ix_recipes_created_at'))
        batch_op.drop_index(batch_op.f('ix_recipes_business_id'))

    op.drop_table('recipes')
    with op.batch_alter_table('quality_passes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_passes_created_by'))
        batch_op.drop_index(batch_op.f('ix_quality_passes_created_at'))
        batch_op.drop_index(batch_op.f('ix_quality_passes_business_id'))

    op.drop_table('quality_passes')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_created_by'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))
        batch_op.drop_index(batch_op.f('ix_projects_contract_id'))

    op.drop_table('projects')
    with op.batch_alter_table('production_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_shifts_created_by'))
        batch_op.drop_index(batch_op.f('ix_production_shifts_created_at'))
        batch_op.drop_index(batch_op.f('ix_production_shifts_business_id'))

    op.drop_table('production_shifts')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_resource'))
        batch_op.drop_index(batch_op.f('ix_permissions_created_by'))
        batch_op.drop_index(batch_op.f('ix_permissions_created_at'))

    op.drop_table('permissions')
    with op.batch_alter_table('period_close', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_close_created_by'))
        batch_op.drop_index(batch_op.f('ix_period_close_created_at'))
        batch_op.drop_index(batch_op.f('ix_period_close_business_id'))

    op.drop_table('period_close')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_created_by'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_orders_business_id'))

    op.drop_table('orders')
    with op.batch_alter_table('limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_limits_created_by'))
        batch_op.drop_index(batch_op.f('ix_limits_created_at'))
        batch_op.drop_index(batch_op.f('ix_limits_business_id'))

    op.drop_table('limits')
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventories_created_by'))
        batch_op.drop_index(batch_op.f('ix_inventories_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventories_business_id'))

    op.drop_table('inventories')
    with op.batch_alter_table('inspection_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_plans_created_by'))
        batch_op.drop_index(batch_op.f('ix_inspection_plans_created_at'))

    op.drop_table('inspection_plans')
    with op.batch_alter_table('inspection_acts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_acts_created_by'))
        batch_op.drop_index(batch_op.f('ix_inspection_acts_created_at'))

    op.drop_table('inspection_acts')
    with op.batch_alter_table('geodesy_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geodesy_requests_created_by'))
        batch_op.drop_index(batch_op.f('ix_geodesy_requests_created_at'))

    op.drop_table('geodesy_requests')
    with op.batch_alter_table('fuel_consumptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_consumptions_created_by'))
        batch_op.drop_index(batch_op.f('ix_fuel_consumptions_created_at'))
        batch_op.drop_index(batch_op.f('ix_fuel_consumptions_business_id'))

    op.drop_table('fuel_consumptions')
    with op.batch_alter_table('fractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fractions_created_by'))
        batch_op.drop_index(batch_op.f('ix_fractions_created_at'))
        batch_op.drop_index(batch_op.f('ix_fractions_business_id'))

    op.drop_table('fractions')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_created_by'))
        batch_op.drop_index(batch_op.f('ix_escalations_created_at'))

    op.drop_table('escalations')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debts_to_business'))
        batch_op.drop_index(batch_op.f('ix_debts_from_business'))
        batch_op.drop_index(batch_op.f('ix_debts_created_by'))
        batch_op.drop_index(batch_op.f('ix_debts_created_at'))

    op.drop_table('debts')
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparties_created_by'))
        batch_op.drop_index(batch_op.f('ix_counterparties_created_at'))

    op.drop_table('counterparties')
    with op.batch_alter_table('construction_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_construction_objects_created_by'))
        batch_op.drop_index(batch_op.f('ix_construction_objects_created_at'))
        batch_op.drop_index(batch_op.f('ix_construction_objects_business_id'))

    op.drop_table('construction_objects')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_created_by'))
        batch_op.drop_index(batch_op.f('ix_clients_created_at'))

    op.drop_table('clients')
    with op.batch_alter_table('cash_registers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_registers_created_by'))
        batch_op.drop_index(batch_op.f('ix_cash_registers_created_at'))
        batch_op.drop_index(batch_op.f('ix_cash_registers_business_id'))

    op.drop_table('cash_registers')
    with op.batch_alter_table('capacity_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capacity_records_created_by'))
        batch_op.drop_index(batch_op.f('ix_capacity_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_capacity_records_business_id'))

    op.drop_table('capacity_records')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_created_by'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_created_at'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_created_by'))
        batch_op.drop_index(batch_op.f('ix_businesses_created_at'))

    op.drop_table('businesses')
    with op.batch_alter_table('barter_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barter_operations_created_by'))
        batch_op.drop_index(batch_op.f('ix_barter_operations_created_at'))

    op.drop_table('barter_operations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_created_by'))
        batch_op.drop_index(batch_op.f('ix_approvals_created_at'))

    op.drop_table('approvals')
    # ### end Alembic commands ###
